---
version: "3.7"

services:
  # ===========================================================================
  # 7hills-cms (http://localhost:8055)
  # ===========================================================================
  cms-cache:
    container_name: 7hills-cms-cache
    image: redis:6
    networks:
      - cms

  cms:
    container_name: 7hills-cms
    image: directus/directus:9
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./cms/uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      - ./cms/database:/directus/database
    networks:
      - cms
    depends_on:
      - cms-cache
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "${CMS_SECRET:?err}"

      DB_CLIENT: "sqlite3"
      DB_FILENAME: "cms.sqlite"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@sehn.dev"
      ADMIN_PASSWORD: "password"

  # ===========================================================================
  # front (http://localhost:3000)
  # ===========================================================================
  front:
    image: 7hills-front:dev
    container_name: 7hills-front
    build:
      context: front
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - "./front:/app"

networks:
  cms:
